//! End-to-end integration tests for git-sourced dependency scanning.
//!
//! T-093-09: exit code is non-zero when a git dep is present (warn-is-non-zero).
//! T-093-05: git dep appears in `--format native` table output (real binary assertion).
//! T-093-06: git dep appears in `--format json` output with correct fields (real binary assertion).
//!
//! These tests drive the real `dep-scan` binary against a Cargo.lock that
//! contains ONLY git-sourced dependencies.  Every registry URL is pointed at
//! `http://127.0.0.1:1` (port 1 is system-reserved; connections are refused
//! immediately by the OS) so any stray registry call fails the test loudly
//! instead of silently succeeding or hanging.
//!
//! The OSV vulnerability lookup is also disabled in the test config, eliminating
//! the last source of outbound network traffic.  The tests are therefore fully
//! offline by design.

use std::io::Write as _;

use assert_cmd::Command;
use predicates::prelude::*;
use tempfile::{NamedTempFile, TempDir};

/// Build a `Command` for the dep-scan binary.
fn dep_scan() -> Command {
    Command::cargo_bin("dep-scan").expect("dep-scan binary must exist")
}

/// A Cargo.lock containing a single git-sourced dependency and no registry deps.
///
/// `source = "git+https://github.com/user/evil-pkg#abcdef1234567890"` is the
/// canonical Cargo.lock representation of a git dependency pinned to a commit SHA.
const GIT_ONLY_CARGO_LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "evil-pkg"
version = "0.1.0"
source = "git+https://github.com/user/evil-pkg#abcdef1234567890"
"#;

/// Write a dep-scan config that:
/// - Points ALL registry URLs at `http://127.0.0.1:1` (immediately-refused loopback port).
/// - Disables vulnerability lookups (OSV) to avoid outbound network calls.
/// - Disables policies that require registry metadata (age, install scripts, etc.).
/// - Points the cache at a tempdir so tests do not share state.
///
/// A stray registry call will return a connection-refused error, causing the
/// test to fail loudly rather than silently passing.
fn write_offline_config(cache_path: &str) -> NamedTempFile {
    // Port 1 is system-reserved; the OS refuses connections immediately without
    // a network round-trip, so any stray registry call errors out fast.
    let dead_url = "http://127.0.0.1:1";

    let mut f = NamedTempFile::new().expect("create temp config");
    writeln!(
        f,
        r#"
min_package_age_hours = 0
cache_path = "{cache_path}"

[registries]
npm_url = "{dead_url}"
pypi_url = "{dead_url}"
crates_url = "{dead_url}"
go_proxy_url = "{dead_url}"
go_sum_db_url = "{dead_url}"

[policies]
check_min_age = false
check_install_scripts = false
check_maintainer_changes = false
check_typosquatting = false
check_vulnerabilities = false
check_obfuscation = false
check_npm_provenance = false
check_pypi_provenance = false
check_go_sumdb = false

[osv]
osv_url = "{dead_url}"

[dependency_confusion]
internal_prefixes = []

[popularity]
min_downloads = 0
"#
    )
    .expect("write temp config");
    f
}

// T-093-09 (real end-to-end) + T-093-05 (native format):
// dep-scan exits non-zero and the native table contains the git dep as WARN.
#[test]
fn t093_09_exit_nonzero_and_t093_05_native_output_contains_git_dep_warn() {
    // T-093-09, T-093-05
    let tmp = TempDir::new().unwrap();
    let cache_path = tmp.path().join("cache.db");
    let config = write_offline_config(cache_path.to_str().unwrap());

    let lockfile_path = tmp.path().join("Cargo.lock");
    std::fs::write(&lockfile_path, GIT_ONLY_CARGO_LOCK).unwrap();

    dep_scan()
        .args([
            "--config",
            config.path().to_str().unwrap(),
            "check",
            "--lockfile",
            lockfile_path.to_str().unwrap(),
            "--lockfile-type",
            "crates",
            "--format",
            "native",
        ])
        // T-093-09: exit code MUST be non-zero (warn verdict → exit 1).
        .assert()
        .code(1)
        // T-093-05: package name must appear in native table output.
        .stdout(predicate::str::contains("evil-pkg"))
        // T-093-05: WARN indicator must appear.
        .stdout(predicate::str::contains("WARN"))
        // T-093-05: git ref must appear in the version column.
        .stdout(predicate::str::contains("abcdef1234567890"))
        // T-093-05: URL must appear in the warning message.
        .stdout(predicate::str::contains("github.com/user/evil-pkg"));
}

// T-093-06 (real end-to-end): --format json output contains the git dep
// with verdict "warn" and a non-empty "reason" (message) field.
//
// Also validates T-093-09 from the JSON exit-code side.
#[test]
fn t093_06_json_output_contains_git_dep_with_warn_verdict_and_nonempty_reason() {
    // T-093-06, T-093-09
    let tmp = TempDir::new().unwrap();
    let cache_path = tmp.path().join("cache.db");
    let config = write_offline_config(cache_path.to_str().unwrap());

    let lockfile_path = tmp.path().join("Cargo.lock");
    std::fs::write(&lockfile_path, GIT_ONLY_CARGO_LOCK).unwrap();

    let output = dep_scan()
        .args([
            "--config",
            config.path().to_str().unwrap(),
            "check",
            "--lockfile",
            lockfile_path.to_str().unwrap(),
            "--lockfile-type",
            "crates",
            "--format",
            "json",
        ])
        .output()
        .expect("dep-scan must run");

    // T-093-09: exit code must be non-zero.
    let status = output.status.code().unwrap_or(-1);
    assert_ne!(
        status, 0,
        "T-093-09: exit code must be non-zero when a git dep is present, got {status}"
    );
    assert_eq!(
        status, 1,
        "T-093-09: expected exit code 1 (warn verdict), got {status}"
    );

    // T-093-06: parse JSON output.
    let stdout = String::from_utf8_lossy(&output.stdout);
    let json: serde_json::Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("T-093-06: stdout must be valid JSON: {e}\nstdout: {stdout}"));

    let arr = json
        .as_array()
        .expect("T-093-06: JSON output must be an array");
    assert_eq!(
        arr.len(),
        1,
        "T-093-06: exactly one result for one git dep, got {}",
        arr.len()
    );

    let elem = &arr[0];

    // T-093-06: verdict must be "warn".
    assert_eq!(
        elem["result"].as_str(),
        Some("warn"),
        "T-093-06: result field must be 'warn', got: {:?}",
        elem["result"]
    );

    // T-093-06: "reason" field must be non-empty.
    let reason = elem["reason"].as_str().unwrap_or("");
    assert!(
        !reason.is_empty(),
        "T-093-06: reason field must be non-empty for a git dep"
    );

    // T-093-06: reason must mention the git URL.
    assert!(
        reason.contains("github.com/user/evil-pkg"),
        "T-093-06: reason must contain the git URL, got: {reason:?}"
    );

    // T-093-06: reason must mention the ref (commit SHA).
    assert!(
        reason.contains("abcdef1234567890"),
        "T-093-06: reason must contain the git ref, got: {reason:?}"
    );

    // T-093-06: package name must be preserved.
    assert_eq!(
        elem["package"].as_str(),
        Some("evil-pkg"),
        "T-093-06: package field must be 'evil-pkg', got: {:?}",
        elem["package"]
    );
}
