//! End-to-end integration tests for the mutable-ref policy (task 094).
//!
//! T-094-21: Mutable-ref warn appears in `--format json` output.
//! T-094-22: Policy fires before any VCS fetch (wiremock stub captures zero requests).
//! T-094-23: No regressions — `cargo test`, clippy, and fmt all pass (pre-commit gate).
//!
//! These tests drive the real `dep-scan` binary against a Cargo.lock that
//! contains a git-sourced dependency pointing at `"main"`.  Every registry URL
//! is pointed at a wiremock server, so any stray registry call would be
//! captured and can be verified as zero.

use std::io::Write as _;

use assert_cmd::Command;
use tempfile::{NamedTempFile, TempDir};
use wiremock::matchers::{method, path_regex};
use wiremock::{Mock, MockServer, ResponseTemplate};

/// Build a `Command` for the dep-scan binary.
fn dep_scan() -> Command {
    Command::cargo_bin("dep-scan").expect("dep-scan binary must exist")
}

/// A Cargo.lock containing one git-sourced dependency pointing at `main`.
const GIT_MAIN_CARGO_LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "my-git-dep"
version = "0.1.0"
source = "git+https://github.com/user/my-git-dep"
"#;

/// A Cargo.lock containing one git-sourced dependency pointing at a pinned SHA.
const GIT_PINNED_CARGO_LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "my-git-dep"
version = "0.1.0"
source = "git+https://github.com/user/my-git-dep#a3b5c7d9e1f2a3b5c7d9e1f2a3b5c7d9e1f2a3b5"
"#;

/// Write a dep-scan config pointing all registries at the given mock server URL.
///
/// All non-git policies are disabled so the only signal is from the mutable-ref
/// policy.  The cache is placed in a tempdir to avoid cross-test sharing.
fn write_mock_config(server_url: &str, cache_path: &str) -> NamedTempFile {
    let mut f = NamedTempFile::new().expect("create temp config");
    writeln!(
        f,
        r#"
min_package_age_hours = 0
cache_path = "{cache_path}"

[registries]
npm_url = "{server_url}"
pypi_url = "{server_url}"
crates_url = "{server_url}"
go_proxy_url = "{server_url}"
go_sum_db_url = "{server_url}"

[policies]
check_min_age = false
check_install_scripts = false
check_maintainer_changes = false
check_typosquatting = false
check_vulnerabilities = false
check_obfuscation = false
check_npm_provenance = false
check_pypi_provenance = false
check_go_sumdb = false
mutable_git_ref = "warn"

[osv]
osv_url = "{server_url}"

[dependency_confusion]
internal_prefixes = []

[popularity]
min_downloads = 0
"#
    )
    .expect("write temp config");
    f
}

// T-094-21: Mutable-ref warn appears in `--format json` output.
//
// A Cargo.lock with a git dep pointing at "main" (empty ref in this case
// since there's no # fragment) must produce a JSON element with:
//   "verdict" (result) = "warn"
//   "message" (reason) containing the ref value or "no ref specified"
//
// The wiremock server is started but no mounts are added; any request would
// return 404.  After the test we verify received_requests() == 0.
#[tokio::test]
async fn t094_21_mutable_ref_warn_in_json_output() {
    // T-094-21
    let mock_server = MockServer::start().await;

    let tmp = TempDir::new().unwrap();
    let cache_path = tmp.path().join("cache.db");
    let config = write_mock_config(&mock_server.uri(), cache_path.to_str().unwrap());

    let lockfile_path = tmp.path().join("Cargo.lock");
    std::fs::write(&lockfile_path, GIT_MAIN_CARGO_LOCK).unwrap();

    let output = dep_scan()
        .args([
            "--config",
            config.path().to_str().unwrap(),
            "check",
            "--lockfile",
            lockfile_path.to_str().unwrap(),
            "--lockfile-type",
            "crates",
            "--format",
            "json",
        ])
        .output()
        .expect("dep-scan must run");

    // Exit code must be non-zero (warn verdict).
    let status = output.status.code().unwrap_or(-1);
    assert_eq!(
        status, 1,
        "T-094-21: exit code must be 1 (warn verdict) for mutable-ref dep, got {status}"
    );

    // Parse JSON output.
    let stdout = String::from_utf8_lossy(&output.stdout);
    let json: serde_json::Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("T-094-21: stdout must be valid JSON: {e}\nstdout: {stdout}"));

    let arr = json
        .as_array()
        .expect("T-094-21: JSON output must be an array");
    assert_eq!(
        arr.len(),
        1,
        "T-094-21: exactly one result, got {}",
        arr.len()
    );

    let elem = &arr[0];

    // T-094-21: verdict must be "warn".
    assert_eq!(
        elem["result"].as_str(),
        Some("warn"),
        "T-094-21: result field must be 'warn', got: {:?}",
        elem["result"]
    );

    // T-094-21: message must contain the ref value or mention "no ref".
    let reason = elem["reason"].as_str().unwrap_or("");
    assert!(
        !reason.is_empty(),
        "T-094-21: reason field must be non-empty for a mutable-ref dep"
    );
    // The empty ref case says "no ref specified"; a named branch case names the ref.
    assert!(
        reason.contains("mutable") || reason.contains("no ref"),
        "T-094-21: reason must mention mutability or 'no ref', got: {reason:?}"
    );

    // T-094-22 (partial): No requests reached the mock server.
    // This proves the mutable-ref policy fired with zero network calls.
    let received = mock_server.received_requests().await.unwrap_or_default();
    assert_eq!(
        received.len(),
        0,
        "T-094-22: wiremock server must have received zero requests; \
         the mutable-ref policy must not make network calls. Got {} request(s): {:?}",
        received.len(),
        received
            .iter()
            .map(|r| format!("{} {}", r.method, r.url))
            .collect::<Vec<_>>()
    );
}

// T-094-22: Policy fires before any VCS fetch (wiremock stub captures zero requests).
//
// Uses a named-branch ref "main" to confirm the policy produces a warn result
// with zero outbound calls.  This is a dedicated test for the network isolation
// requirement.
#[tokio::test]
async fn t094_22_no_network_calls_for_mutable_ref_policy() {
    // T-094-22
    let mock_server = MockServer::start().await;

    // Mount a catch-all mock that would record any request reaching the server.
    // We then assert it received zero requests after the scan.
    Mock::given(method("GET"))
        .and(path_regex(".*"))
        .respond_with(ResponseTemplate::new(200).set_body_string("{}"))
        .mount(&mock_server)
        .await;

    let tmp = TempDir::new().unwrap();
    let cache_path = tmp.path().join("cache.db");

    // Use a lockfile with a git dep pointing at "main" (via a branch shorthand —
    // the ref is extracted from the # fragment; no fragment means empty ref here).
    let lockfile_path = tmp.path().join("Cargo.lock");
    std::fs::write(&lockfile_path, GIT_MAIN_CARGO_LOCK).unwrap();

    let config = write_mock_config(&mock_server.uri(), cache_path.to_str().unwrap());

    dep_scan()
        .args([
            "--config",
            config.path().to_str().unwrap(),
            "check",
            "--lockfile",
            lockfile_path.to_str().unwrap(),
            "--lockfile-type",
            "crates",
            "--format",
            "json",
        ])
        .output()
        .expect("dep-scan must run");

    // After the scan, the mock server must have received zero requests.
    // Any non-zero count means the policy (or something on the git-dep path)
    // made a network call it should not have.
    let received = mock_server.received_requests().await.unwrap_or_default();
    assert_eq!(
        received.len(),
        0,
        "T-094-22: wiremock server must have received zero requests for a git dep; \
         the mutable-ref policy must be network-free. Got {} request(s): {:?}",
        received.len(),
        received
            .iter()
            .map(|r| format!("{} {}", r.method, r.url))
            .collect::<Vec<_>>()
    );
}

// Bonus: Verify that a pinned ref (40-hex SHA) produces a "pass" result
// (T-094-12 from the integration side).
#[tokio::test]
async fn t094_pinned_ref_passes_in_json_output() {
    let mock_server = MockServer::start().await;

    let tmp = TempDir::new().unwrap();
    let cache_path = tmp.path().join("cache.db");
    let config = write_mock_config(&mock_server.uri(), cache_path.to_str().unwrap());

    let lockfile_path = tmp.path().join("Cargo.lock");
    std::fs::write(&lockfile_path, GIT_PINNED_CARGO_LOCK).unwrap();

    let output = dep_scan()
        .args([
            "--config",
            config.path().to_str().unwrap(),
            "check",
            "--lockfile",
            lockfile_path.to_str().unwrap(),
            "--lockfile-type",
            "crates",
            "--format",
            "json",
        ])
        .output()
        .expect("dep-scan must run");

    // Pinned ref: exit code must be 0 (pass).
    let status = output.status.code().unwrap_or(-1);
    assert_eq!(
        status, 0,
        "T-094-12 integration: exit code must be 0 for a pinned SHA ref, got {status}"
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    let json: serde_json::Value = serde_json::from_str(&stdout)
        .unwrap_or_else(|e| panic!("stdout must be valid JSON: {e}\nstdout: {stdout}"));
    let arr = json.as_array().expect("JSON output must be an array");
    assert_eq!(arr.len(), 1, "exactly one result");
    assert_eq!(
        arr[0]["result"].as_str(),
        Some("pass"),
        "pinned ref must produce 'pass', got: {:?}",
        arr[0]["result"]
    );

    // Zero network calls for pinned refs too.
    let received = mock_server.received_requests().await.unwrap_or_default();
    assert_eq!(
        received.len(),
        0,
        "zero network calls expected for git dep with pinned SHA, got {}",
        received.len()
    );
}
