// SPDX-License-Identifier: Apache-2.0
//! End-to-end non-regression test for the [transitive] config block (task 107).
//!
//! T-107-14: [transitive] enabled=false produces stdout and exit code that are
//!           byte-for-byte identical to a scan with no [transitive] block at all.
//!           This is a genuine binary-invocation test: the real dep-scan binary is
//!           run twice against the same offline Cargo.lock fixture.
//!
//! Zero network I/O: all registry URLs point at 127.0.0.1:1 (system-reserved
//! port — OS refuses immediately); the single git dep's host is denied before any
//! socket is opened (REQ-096-03).

use std::io::Write as _;

use assert_cmd::Command;
use tempfile::{NamedTempFile, TempDir};

/// Build a `Command` for the dep-scan binary.
fn dep_scan() -> Command {
    Command::cargo_bin("dep-scan").expect("dep-scan binary must exist")
}

/// A Cargo.lock containing a single git-sourced dependency and no registry deps.
///
/// The dep is git-sourced, so the scan arm never touches any registry URL:
/// the host is denied immediately (REQ-096-03), yielding a Warn verdict with
/// no outbound network traffic.
const GIT_ONLY_CARGO_LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "test-pkg"
version = "0.1.0"
source = "git+https://github.com/example/test-pkg#abcdef1234567890abcdef1234567890abcde123"
"#;

/// Write a dep-scan config with NO [transitive] block (flat-scan baseline).
///
/// All registry URLs and OSV point at 127.0.0.1:1; the git dep's host is denied,
/// making the run fully offline.
fn write_flat_config(cache_path: &str) -> NamedTempFile {
    // Escape backslashes so Windows paths (C:\Users\...) are valid TOML basic
    // strings; on Unix this is a no-op. The escaped path round-trips back to the
    // original value after TOML parsing, so stderr-path assertions still match.
    let cache_path = cache_path.replace('\\', "\\\\");
    let dead_url = "http://127.0.0.1:1";
    let mut f = NamedTempFile::new().expect("create temp config");
    writeln!(
        f,
        r#"min_package_age_hours = 0
cache_path = "{cache_path}"

[registries]
npm_url = "{dead_url}"
pypi_url = "{dead_url}"
crates_url = "{dead_url}"
go_proxy_url = "{dead_url}"
go_sum_db_url = "{dead_url}"

[policies]
check_min_age = false
check_install_scripts = false
check_maintainer_changes = false
check_typosquatting = false
check_vulnerabilities = false
check_obfuscation = false
check_npm_provenance = false
check_pypi_provenance = false
check_go_sumdb = false

[osv]
osv_url = "{dead_url}"

[dependency_confusion]
internal_prefixes = []

[popularity]
min_downloads = 0

[vcs]
denied_hosts = ["github.com"]
fetch_timeout_secs = 3
"#
    )
    .expect("write temp config");
    f
}

/// Write the same config but WITH `[transitive] enabled = false` appended.
///
/// Everything else is identical to `write_flat_config`.  When transitive is
/// disabled it must not alter any observable output (REQ-107-04).
fn write_transitive_disabled_config(cache_path: &str) -> NamedTempFile {
    // Escape backslashes so Windows paths (C:\Users\...) are valid TOML basic
    // strings; on Unix this is a no-op. The escaped path round-trips back to the
    // original value after TOML parsing, so stderr-path assertions still match.
    let cache_path = cache_path.replace('\\', "\\\\");
    let dead_url = "http://127.0.0.1:1";
    let mut f = NamedTempFile::new().expect("create temp config");
    writeln!(
        f,
        r#"min_package_age_hours = 0
cache_path = "{cache_path}"

[registries]
npm_url = "{dead_url}"
pypi_url = "{dead_url}"
crates_url = "{dead_url}"
go_proxy_url = "{dead_url}"
go_sum_db_url = "{dead_url}"

[policies]
check_min_age = false
check_install_scripts = false
check_maintainer_changes = false
check_typosquatting = false
check_vulnerabilities = false
check_obfuscation = false
check_npm_provenance = false
check_pypi_provenance = false
check_go_sumdb = false

[osv]
osv_url = "{dead_url}"

[dependency_confusion]
internal_prefixes = []

[popularity]
min_downloads = 0

[vcs]
denied_hosts = ["github.com"]
fetch_timeout_secs = 3

[transitive]
enabled = false
"#
    )
    .expect("write temp config");
    f
}

// T-107-14: [transitive] enabled=false produces byte-for-byte identical stdout
// and exit code compared to a scan with NO [transitive] block.
//
// Two real dep-scan binary invocations against the same offline Cargo.lock:
//   Scan A — config has no [transitive] block (flat-scan baseline).
//   Scan B — config is identical but adds `[transitive] enabled = false`.
// Both stdout and exit code must be byte-for-byte identical.
//
// Zero network: all registry URLs point at 127.0.0.1:1 (connection refused
// immediately by the OS) and the git dep's host is denied before any socket
// is opened (REQ-096-03).
#[test]
fn t107_14_enabled_false_non_regression_e2e() {
    // T-107-14
    let tmp_a = TempDir::new().unwrap();
    let tmp_b = TempDir::new().unwrap();

    let cache_a = tmp_a.path().join("cache.db");
    let cache_b = tmp_b.path().join("cache.db");

    let config_a = write_flat_config(cache_a.to_str().unwrap());
    let config_b = write_transitive_disabled_config(cache_b.to_str().unwrap());

    // Write the same lockfile into both tempdirs.
    let lockfile_a = tmp_a.path().join("Cargo.lock");
    let lockfile_b = tmp_b.path().join("Cargo.lock");
    std::fs::write(&lockfile_a, GIT_ONLY_CARGO_LOCK).unwrap();
    std::fs::write(&lockfile_b, GIT_ONLY_CARGO_LOCK).unwrap();

    // Scan A: flat scan (no [transitive] block).
    let output_a = dep_scan()
        .args([
            "--config",
            config_a.path().to_str().unwrap(),
            "check",
            "--lockfile",
            lockfile_a.to_str().unwrap(),
            "--lockfile-type",
            "crates",
            "--format",
            "native",
        ])
        .output()
        .expect("T-107-14: dep-scan (scan A — no [transitive] block) must run without panic");

    // Scan B: same but with [transitive] enabled = false.
    let output_b = dep_scan()
        .args([
            "--config",
            config_b.path().to_str().unwrap(),
            "check",
            "--lockfile",
            lockfile_b.to_str().unwrap(),
            "--lockfile-type",
            "crates",
            "--format",
            "native",
        ])
        .output()
        .expect("T-107-14: dep-scan (scan B — [transitive] enabled=false) must run without panic");

    // Assert exit codes are identical.
    let exit_a = output_a.status.code().unwrap_or(-1);
    let exit_b = output_b.status.code().unwrap_or(-1);
    assert_eq!(
        exit_a, exit_b,
        "T-107-14: exit codes must be identical: \
         scan_a (no [transitive])={exit_a} \
         scan_b ([transitive] enabled=false)={exit_b}"
    );

    // Assert stdout bytes are byte-for-byte identical.
    let stdout_a = String::from_utf8_lossy(&output_a.stdout);
    let stdout_b = String::from_utf8_lossy(&output_b.stdout);
    assert_eq!(
        stdout_a, stdout_b,
        "T-107-14: stdout must be byte-for-byte identical:\n\
         scan_a (no [transitive]):\n{stdout_a}\n\
         scan_b ([transitive] enabled=false):\n{stdout_b}"
    );

    // Sanity: both scans actually produced non-empty output (not vacuous).
    assert!(
        !stdout_a.is_empty(),
        "T-107-14: stdout must be non-empty — the scan must actually execute against the fixture"
    );
}
